title: 朝霞キャンパス 学生ポータル
description: 東洋大学 朝霞キャンパス 生命科学部・食環境科学部 学生用ポータルサイト
baseurl: "/asaka-portal"
url: "https://yuhei-tsujimoto.github.io"

remote_theme: just-the-docs/just-the-docs

# 検索機能を有効化
search_enabled: true

# ナビゲーション設定
nav_sort: case_insensitive

plugins:
  - jekyll-feed
  - jekyll-seo-tag
